// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgHvxDpT8O-8wTYBCm5KfZ7ZzweYk7iI',
    appId: '1:77948975595:web:e245f2ad18980a5e6401ae',
    messagingSenderId: '77948975595',
    projectId: 'flutter-note-app-4165b',
    authDomain: 'flutter-note-app-4165b.firebaseapp.com',
    storageBucket: 'flutter-note-app-4165b.appspot.com',
    measurementId: 'G-5GTKDCVH2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVp-szUDXJoIn27IemG4SEp9LAh_CFlQs',
    appId: '1:77948975595:android:719253c3a058d4646401ae',
    messagingSenderId: '77948975595',
    projectId: 'flutter-note-app-4165b',
    storageBucket: 'flutter-note-app-4165b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhb0F6jNNkJjB_v0Wqd3-ez_IBnVlL5tg',
    appId: '1:77948975595:ios:6297c1a51d3fd16b6401ae',
    messagingSenderId: '77948975595',
    projectId: 'flutter-note-app-4165b',
    storageBucket: 'flutter-note-app-4165b.appspot.com',
    iosBundleId: 'com.example.noteListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhb0F6jNNkJjB_v0Wqd3-ez_IBnVlL5tg',
    appId: '1:77948975595:ios:3627e96c0b49206e6401ae',
    messagingSenderId: '77948975595',
    projectId: 'flutter-note-app-4165b',
    storageBucket: 'flutter-note-app-4165b.appspot.com',
    iosBundleId: 'com.example.noteListApp.RunnerTests',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
